use crate::startup::AppLanguage;

pub(super) fn core_workflow_lines(language: AppLanguage) -> &'static [&'static str] {
    match language {
        AppLanguage::English => CORE_WORKFLOW_LINES_EN,
        AppLanguage::SimplifiedChinese => CORE_WORKFLOW_LINES_ZH_CN,
    }
}

pub(super) fn local_integration_lines(language: AppLanguage) -> &'static [&'static str] {
    match language {
        AppLanguage::English => LOCAL_INTEGRATION_LINES_EN,
        AppLanguage::SimplifiedChinese => LOCAL_INTEGRATION_LINES_ZH_CN,
    }
}

pub(super) fn remote_capable_lines(language: AppLanguage) -> &'static [&'static str] {
    match language {
        AppLanguage::English => REMOTE_CAPABLE_LINES_EN,
        AppLanguage::SimplifiedChinese => REMOTE_CAPABLE_LINES_ZH_CN,
    }
}

const CORE_WORKFLOW_LINES_EN: &[&str] = &[
    "  /help                Show this help message",
    "  /shortcuts           Show keyboard shortcuts and input affordances",
    "  /status              Show current REPL status",
    "  /doctor              Inspect local config, providers, and storage health",
    "  /usage               Show persisted workspace activity totals",
    "  /stats               Show detailed persisted workspace statistics",
    "  /cost                Show estimated persisted token cost",
    "  /brief               Show the current workspace brief",
    "  /brief set <message> Store a local brief for the current workspace",
    "  /brief clear         Remove the current workspace brief",
    "  /tools <query>       Search available local tools by name or description",
    "  /plan                Show current planning state for this session",
    "  /plan panel [n]      Show a plan dashboard or focus one accepted step",
    "  /plan enter          Enable plan mode for this session",
    "  /plan add [--index <n>] <status>:<text> Insert or append an accepted plan step",
    "  /plan update <n> <status>:<text> Replace an accepted plan step",
    "  /plan remove <n>     Remove an accepted plan step",
    "  /plan allow <prompt> Add an allowed follow-up prompt",
    "  /plan disallow <prompt> Remove an allowed follow-up prompt",
    "  /plan exit --step <status>:<text>... Store an accepted plan and leave plan mode",
    "  /plan clear          Clear accepted plan state for this session",
    "  /install             Show local install status and stable target paths",
    "  /install plan [source] [target] Plan an offline local install",
    "  /install apply [source] [target] [--force] Copy a local binary into the stable install target",
    "  /upgrade             Show local upgrade status",
    "  /upgrade plan <source> [target] Plan an offline local upgrade",
    "  /upgrade apply <source> [target] [--backup] [--force] Replace the stable local install",
    "  /output-style        Show active, default, and discovered output styles",
    "  /output-style panel [name] Show an output-style dashboard or inspect one style",
    "  /output-style use <name> Apply an output style to the current session",
    "  /persona             Show active, default, and discovered personas",
    "  /persona panel [name] Show a persona dashboard or inspect one persona",
    "  /persona use <name>  Apply a persona to the current session",
    "  /fragment            Show active, default, and discovered prompt fragments",
    "  /fragment panel [name] Show a prompt-fragment dashboard or inspect one fragment",
    "  /fragment use <name> [name...] Apply prompt fragments to the current session",
    "  /search <query>      Search transcript, persisted sessions, and memory",
    "  /skills [name]       List skills or show a skill definition",
    "  /hooks [name]        List hooks or show a hook definition",
    "  /workflow            List project workflow scripts",
    "  /workflow dashboard [name] Open the interactive workflow dashboard shell",
    "  /workflow dashboard --script-path <path> Open one explicit workflow dashboard shell",
    "  /workflow overview [name] Show a selector-style workflow overview",
    "  /workflow overview --script-path <path> Show one explicit workflow overview",
    "  /workflow panel [name] [n] Show an authoring panel with copyable edit actions",
    "  /workflow panel --script-path <path> [n] Open an explicit workflow script",
    "  /workflow runs [name] List recorded workflow runs",
    "  /workflow runs --script-path <path> List recorded runs for one explicit script",
    "  /workflow validate [name] Validate workflow scripts",
    "  /workflow validate --script-path <path> Validate one explicit workflow script",
    "  /workflow show-run <id> [n] Show a recorded workflow run",
    "  /workflow last-run [name] [n] Show the latest recorded workflow run",
    "  /workflow last-run --script-path <path> [n] Show the latest recorded run for one explicit script",
    "  /workflow show <name> Show a workflow script definition",
    "  /workflow show --script-path <path> Show one explicit workflow script",
    "  /workflow init <name> Create a starter workflow script",
    "  /workflow add-step <name> --prompt <text> Add a workflow step",
    "  /workflow add-step --script-path <path> --prompt <text> Add a step to an explicit script",
    "  /workflow update-step <name> <n> ... Edit a workflow step",
    "  /workflow update-step --script-path <path> <n> ... Edit an explicit workflow script",
    "  /workflow duplicate-step <name> <n> [--to <m>] Duplicate a workflow step",
    "  /workflow duplicate-step --script-path <path> <n> [--to <m>] Duplicate a step in an explicit workflow script",
    "  /workflow move-step <name> <n> --to <m> Reorder a workflow step",
    "  /workflow move-step --script-path <path> <n> --to <m> Reorder a step in an explicit workflow script",
    "  /workflow remove-step <name> <n> Remove a workflow step",
    "  /workflow remove-step --script-path <path> <n> Remove a step from an explicit workflow script",
    "  /workflow set-shared-context <name> <text> Set workflow shared context",
    "  /workflow set-shared-context --script-path <path> <text> Set shared context on an explicit workflow script",
    "  /workflow clear-shared-context <name> Clear workflow shared context",
    "  /workflow clear-shared-context --script-path <path> Clear shared context on an explicit workflow script",
    "  /workflow enable-continue-on-error <name> Enable continue_on_error",
    "  /workflow enable-continue-on-error --script-path <path> Enable continue_on_error on an explicit workflow script",
    "  /workflow disable-continue-on-error <name> Disable continue_on_error",
    "  /workflow disable-continue-on-error --script-path <path> Disable continue_on_error on an explicit workflow script",
    "  /workflow run <name> [shared_context] Run a workflow script locally",
    "  /workflow run --script-path <path> [shared_context] Run one explicit workflow script",
    "  focused workflow panel/dashboard: `name <text>` / `prompt <text>` / `when <json>` / `model <name>` / `backend <name>` / `step-cwd <path>`",
    "  focused workflow panel/dashboard: `clear-name` / `clear-when` / `clear-model` / `clear-backend` / `clear-step-cwd`",
    "  focused workflow panel/dashboard: `background` / `foreground` / `dup [to]` / `move <to>` / `rm`",
    "  focused workflow dashboard: `open <n>` / `back`",
    "  focused workflow panel/show-run/dashboard: `first` / `prev` / `next` / `last`",
];

const CORE_WORKFLOW_LINES_ZH_CN: &[&str] = &[
    "  /help                显示这条帮助信息",
    "  /shortcuts           显示快捷键与输入提示",
    "  /status              显示当前 REPL 状态",
    "  /doctor              检查本地配置、provider 与存储健康状态",
    "  /usage               显示工作区持久化活动汇总",
    "  /stats               显示工作区详细持久化统计",
    "  /cost                显示持久化 token 预估成本",
    "  /brief               显示当前工作区 brief",
    "  /brief set <message> 为当前工作区保存本地 brief",
    "  /brief clear         移除当前工作区 brief",
    "  /tools <query>       按名称或描述搜索本地可用工具",
    "  /plan                显示当前会话的计划状态",
    "  /plan panel [n]      显示计划面板或聚焦一个已接受步骤",
    "  /plan enter          为当前会话启用计划模式",
    "  /plan add [--index <n>] <status>:<text> 插入或追加一个已接受步骤",
    "  /plan update <n> <status>:<text> 替换一个已接受步骤",
    "  /plan remove <n>     移除一个已接受步骤",
    "  /plan allow <prompt> 添加允许的后续提示",
    "  /plan disallow <prompt> 移除允许的后续提示",
    "  /plan exit --step <status>:<text>... 保存已接受计划并退出计划模式",
    "  /plan clear          清空当前会话的已接受计划状态",
    "  /install             显示本地安装状态与稳定目标路径",
    "  /install plan [source] [target] 规划离线本地安装",
    "  /install apply [source] [target] [--force] 将本地二进制复制到稳定安装目标",
    "  /upgrade             显示本地升级状态",
    "  /upgrade plan <source> [target] 规划离线本地升级",
    "  /upgrade apply <source> [target] [--backup] [--force] 替换稳定本地安装",
    "  /output-style        显示当前、默认与已发现的输出风格",
    "  /output-style panel [name] 显示输出风格面板或查看某个风格",
    "  /output-style use <name> 为当前会话应用一个输出风格",
    "  /persona             显示当前、默认与已发现的人设",
    "  /persona panel [name] 显示人设面板或查看某个人设",
    "  /persona use <name>  为当前会话应用一个人设",
    "  /fragment            显示当前、默认与已发现的提示片段",
    "  /fragment panel [name] 显示提示片段面板或查看某个片段",
    "  /fragment use <name> [name...] 为当前会话应用提示片段",
    "  /search <query>      搜索当前转录、已持久化会话与记忆",
    "  /skills [name]       列出技能或查看某个技能定义",
    "  /hooks [name]        列出 hooks 或查看某个 hook 定义",
    "  /workflow            列出项目工作流脚本",
    "  /workflow dashboard [name] 打开交互式工作流仪表板 shell",
    "  /workflow dashboard --script-path <path> 打开指定工作流仪表板 shell",
    "  /workflow overview [name] 显示选择器风格的工作流概览",
    "  /workflow overview --script-path <path> 显示指定工作流概览",
    "  /workflow panel [name] [n] 显示可复制编辑动作的工作流面板",
    "  /workflow panel --script-path <path> [n] 打开指定工作流脚本",
    "  /workflow runs [name] 列出已记录的工作流运行",
    "  /workflow runs --script-path <path> 列出指定脚本的运行记录",
    "  /workflow validate [name] 校验工作流脚本",
    "  /workflow validate --script-path <path> 校验指定工作流脚本",
    "  /workflow show-run <id> [n] 显示一条工作流运行记录",
    "  /workflow last-run [name] [n] 显示最新工作流运行记录",
    "  /workflow last-run --script-path <path> [n] 显示指定脚本的最新运行记录",
    "  /workflow show <name> 显示工作流脚本定义",
    "  /workflow show --script-path <path> 显示指定工作流脚本",
    "  /workflow init <name> 创建起始工作流脚本",
    "  /workflow add-step <name> --prompt <text> 添加工作流步骤",
    "  /workflow add-step --script-path <path> --prompt <text> 为指定脚本添加步骤",
    "  /workflow update-step <name> <n> ... 编辑工作流步骤",
    "  /workflow update-step --script-path <path> <n> ... 编辑指定脚本中的步骤",
    "  /workflow duplicate-step <name> <n> [--to <m>] 复制工作流步骤",
    "  /workflow duplicate-step --script-path <path> <n> [--to <m>] 复制指定脚本中的步骤",
    "  /workflow move-step <name> <n> --to <m> 重新排序工作流步骤",
    "  /workflow move-step --script-path <path> <n> --to <m> 重新排序指定脚本中的步骤",
    "  /workflow remove-step <name> <n> 移除工作流步骤",
    "  /workflow remove-step --script-path <path> <n> 移除指定脚本中的步骤",
    "  /workflow set-shared-context <name> <text> 设置工作流共享上下文",
    "  /workflow set-shared-context --script-path <path> <text> 为指定脚本设置共享上下文",
    "  /workflow clear-shared-context <name> 清空工作流共享上下文",
    "  /workflow clear-shared-context --script-path <path> 清空指定脚本的共享上下文",
    "  /workflow enable-continue-on-error <name> 启用 continue_on_error",
    "  /workflow enable-continue-on-error --script-path <path> 为指定脚本启用 continue_on_error",
    "  /workflow disable-continue-on-error <name> 禁用 continue_on_error",
    "  /workflow disable-continue-on-error --script-path <path> 为指定脚本禁用 continue_on_error",
    "  /workflow run <name> [shared_context] 在本地运行工作流脚本",
    "  /workflow run --script-path <path> [shared_context] 在本地运行指定工作流脚本",
    "  focused workflow panel/dashboard: `name <text>` / `prompt <text>` / `when <json>` / `model <name>` / `backend <name>` / `step-cwd <path>` 用于编辑当前聚焦步骤",
    "  focused workflow panel/dashboard: `clear-name` / `clear-when` / `clear-model` / `clear-backend` / `clear-step-cwd` 用于清空当前聚焦字段",
    "  focused workflow panel/dashboard: `background` / `foreground` / `dup [to]` / `move <to>` / `rm` 用于调整当前聚焦步骤",
    "  focused workflow dashboard: `open <n>` / `back` 用于进入或返回视图",
    "  focused workflow panel/show-run/dashboard: `first` / `prev` / `next` / `last` 用于导航步骤",
];

const LOCAL_INTEGRATION_LINES_EN: &[&str] = &[
    "  /bridge              Show local bridge runtime status",
    "  /bridge panel [id]   Show a bridge panel or inspect one persisted session",
    "  /bridge sessions     List persisted bridge sessions",
    "  /bridge show <id>    Show bridge session details",
    "  /ide                 Show IDE-facing bridge status",
    "  /ide panel           Show an IDE-facing bridge overview panel",
    "  /mcp                 List configured MCP servers",
    "  /mcp panel [name]    Show an MCP dashboard or inspect one server",
    "  /mcp show <name>     Show a configured MCP server",
    "  /mcp tools <name>    List tools exposed by a configured MCP server",
    "  /mcp call <name> <tool> [json] Call an MCP tool with optional JSON input",
    "  /mcp resources <name> List MCP resources exposed by a configured server",
    "  /mcp prompts <name>  List MCP prompts exposed by a configured server",
    "  /mcp read-resource <name> <uri> Read a resource from a configured MCP server",
    "  /mcp get-prompt <name> <prompt> [json] Fetch an MCP prompt with optional JSON input",
    "  /mcp auth ...        Show, set, or clear MCP bearer-token helper state",
    "  /mcp auth oauth-set <name> <client-id> <authorize-url> <token-url> <redirect-url> [scope...] Configure OAuth client settings",
    "  /mcp auth oauth-start <name> Start an OAuth PKCE flow for a configured MCP server",
    "  /mcp auth oauth-exchange <name> <code> <verifier> Exchange an OAuth code for tokens",
    "  /mcp auth oauth-refresh <name> Refresh a linked MCP OAuth access token",
    "  /mcp auth oauth-clear <name> Clear the linked MCP OAuth account",
    "  /mcp registry list [cursor] [limit] Browse the official MCP registry",
    "  /mcp registry show <name> Show the latest registry metadata for a server",
    "  /mcp registry install <name> [server-name] [scope] Install a registry server into local config",
    "  /mcp add ...         Add a stdio, SSE, or WS MCP server",
    "  /mcp enable <name>   Enable a configured MCP server",
    "  /mcp disable <name>  Disable a configured MCP server",
    "  /mcp remove <name>   Remove a configured MCP server",
    "  /plugin              List installed plugins",
    "  /plugin panel [id]   Show a plugin dashboard or inspect one plugin",
    "  /plugin show <id>    Show an installed plugin",
    "  /plugin install <path> Install a local plugin package",
    "  /plugin enable <id>  Enable an installed plugin",
    "  /plugin disable <id> Disable an installed plugin",
    "  /plugin remove <id>  Remove an installed plugin",
    "  /plugin marketplace  List configured marketplaces",
];

const LOCAL_INTEGRATION_LINES_ZH_CN: &[&str] = &[
    "  /bridge              显示本地 bridge 运行状态",
    "  /bridge panel [id]   显示 bridge 面板或查看某个已持久化会话",
    "  /bridge sessions     列出已持久化的 bridge 会话",
    "  /bridge show <id>    显示 bridge 会话详情",
    "  /ide                 显示面向 IDE 的 bridge 状态",
    "  /ide panel           显示面向 IDE 的 bridge 概览面板",
    "  /mcp                 列出已配置的 MCP 服务器",
    "  /mcp panel [name]    显示 MCP 面板或查看某个服务器",
    "  /mcp show <name>     显示一个已配置的 MCP 服务器",
    "  /mcp tools <name>    列出某个 MCP 服务器公开的工具",
    "  /mcp call <name> <tool> [json] 调用 MCP 工具，可选传入 JSON",
    "  /mcp resources <name> 列出某个 MCP 服务器公开的资源",
    "  /mcp prompts <name>  列出某个 MCP 服务器公开的 prompts",
    "  /mcp read-resource <name> <uri> 读取某个 MCP 服务器资源",
    "  /mcp get-prompt <name> <prompt> [json] 获取 MCP prompt，可选传入 JSON",
    "  /mcp auth ...        显示、设置或清理 MCP bearer token 辅助状态",
    "  /mcp auth oauth-set <name> <client-id> <authorize-url> <token-url> <redirect-url> [scope...] 配置 OAuth 客户端设置",
    "  /mcp auth oauth-start <name> 为某个 MCP 服务器启动 OAuth PKCE 流程",
    "  /mcp auth oauth-exchange <name> <code> <verifier> 用 OAuth code 交换 token",
    "  /mcp auth oauth-refresh <name> 刷新已关联的 MCP OAuth access token",
    "  /mcp auth oauth-clear <name> 清理已关联的 MCP OAuth 账号",
    "  /mcp registry list [cursor] [limit] 浏览官方 MCP 注册表",
    "  /mcp registry show <name> 显示某个服务器的最新注册表元数据",
    "  /mcp registry install <name> [server-name] [scope] 将注册表服务器安装到本地配置",
    "  /mcp add ...         添加 stdio、SSE 或 WS MCP 服务器",
    "  /mcp enable <name>   启用某个已配置的 MCP 服务器",
    "  /mcp disable <name>  禁用某个已配置的 MCP 服务器",
    "  /mcp remove <name>   移除某个已配置的 MCP 服务器",
    "  /plugin              列出已安装插件",
    "  /plugin panel [id]   显示插件面板或查看某个插件",
    "  /plugin show <id>    显示一个已安装插件",
    "  /plugin install <path> 安装本地插件包",
    "  /plugin enable <id>  启用一个已安装插件",
    "  /plugin disable <id> 禁用一个已安装插件",
    "  /plugin remove <id>  移除一个已安装插件",
    "  /plugin marketplace  列出已配置插件市场",
];

const REMOTE_CAPABLE_LINES_EN: &[&str] = &[
    "  /remote-env          List configured remote environments",
    "  /remote-env panel [name] Show a remote-environment panel or inspect one target",
    "  /remote-env add ...  Add a remote environment profile",
    "  /teleport panel ...  Open a direct-connect teleport plan panel",
    "  /teleport plan ...   Build a raw direct-connect teleport plan",
    "  /teleport connect .. Create a remote direct-connect session",
    "  /assistant           Open the assistant viewer panel",
    "  /assistant show <id> Inspect one assistant-viewable session",
    "  /memory              Show current session memory or fall back to project memory",
    "  /memory panel [--archived] [id] Show a memory dashboard or inspect one memory file",
    "  /memory list [--archived] List captured memory files",
    "  /memory show [--archived] <id> Show a captured memory file",
    "  /memory search [--archived] <query> Search memory files with relevance and age ranking",
    "  /memory clusters [--archived] [--limit <n>] [--semantic] Cluster memory files by token overlap or TF-IDF cosine similarity",
    "  /memory prune [--scope <all|session|project>] [--older-than-days <n>] [--keep-latest <n>] [--apply]",
    "  /memory archive [--scope <all|session|project>] [--older-than-days <n>] [--keep-latest <n>] [--apply]",
    "  /memory decay [--scope <all|session|project>] [--older-than-days <n>] [--keep-latest <n>] [--max-summary-lines <n>] [--max-summary-chars <n>] [--apply]",
    "  /memory save [instructions] Capture memory from the current session",
    "  /session             Show current session metadata",
    "  /session panel [id]  Show a session dashboard or inspect one persisted session",
    "  /session list        List persisted sessions",
    "  /session show <id>   Show persisted session details",
    "  /session share <id> [path] Export a persisted session transcript",
    "  /tasks               List workspace tasks",
    "  /tasks panel [id]    Show a task dashboard or inspect one task",
    "  /tasks add <text>    Add a workspace task",
    "  /tasks show <id>     Show a single workspace task",
    "  /tasks update <id> --status <value> [--output <text>] ... Update task fields",
    "  /tasks output <id>   Show the latest stored task output",
    "  /tasks stop <id> [reason] Cancel a task and optionally record a reason",
    "  /tasks start <id>    Mark a task in progress",
    "  /tasks done <id>     Mark a task completed",
    "  /tasks cancel <id>   Mark a task cancelled",
    "  /tasks remove <id>   Delete a task",
    "  /tasks clear <mode>  Clear `completed` or `all` tasks",
    "  /model               Show the active session model",
    "  /model panel [name]  Show a model dashboard or inspect one profile",
    "  /model list          List configured model profiles",
    "  /model show [name]   Show the current or named model profile",
    "  /model use <name>    Switch the active session model",
    "  /model default <name> Persist the default model profile",
    "  /permissions [mode] Show or switch the permission mode",
    "  /config              Show active config path and resolved config",
    "  /config panel [key]  Show a config dashboard or focus one resolved key",
    "  /config path|keys    Show active config path or supported writable keys",
    "  /config set <key> <value> Update a supported config key",
    "  /config clear <key>  Clear a supported optional config key",
    "  /resume [session-id] List resumable sessions or switch to one",
    "  /share [path]        Export the current transcript as Markdown",
    "  /compact [instructions] Replace history with a summary context",
    "  /rewind             Remove the most recent conversation turn",
    "  /clear               Clear the current conversation history",
    "  /exit                Exit the REPL",
];

const REMOTE_CAPABLE_LINES_ZH_CN: &[&str] = &[
    "  /remote-env          列出已配置的远程环境",
    "  /remote-env panel [name] 显示远程环境面板或查看某个目标",
    "  /remote-env add ...  添加一个远程环境配置",
    "  /teleport panel ...  打开直连 teleport 计划面板",
    "  /teleport plan ...   构建原始直连 teleport 计划",
    "  /teleport connect .. 创建一个远程直连会话",
    "  /assistant           打开 assistant 查看器面板",
    "  /assistant show <id> 查看一个可供 assistant 展示的会话",
    "  /memory              显示当前会话记忆，或回退到项目记忆",
    "  /memory panel [--archived] [id] 显示记忆面板或查看某个记忆文件",
    "  /memory list [--archived] 列出已捕获记忆文件",
    "  /memory show [--archived] <id> 显示一个记忆文件",
    "  /memory search [--archived] <query> 按相关性和时间搜索记忆文件",
    "  /memory clusters [--archived] [--limit <n>] [--semantic] 按 token 重叠或 TF-IDF 余弦相似度聚类记忆",
    "  /memory prune [--scope <all|session|project>] [--older-than-days <n>] [--keep-latest <n>] [--apply]",
    "  /memory archive [--scope <all|session|project>] [--older-than-days <n>] [--keep-latest <n>] [--apply]",
    "  /memory decay [--scope <all|session|project>] [--older-than-days <n>] [--keep-latest <n>] [--max-summary-lines <n>] [--max-summary-chars <n>] [--apply]",
    "  /memory save [instructions] 从当前会话捕获记忆",
    "  /session             显示当前会话元数据",
    "  /session panel [id]  显示会话面板或查看某个已持久化会话",
    "  /session list        列出已持久化会话",
    "  /session show <id>   显示会话详情",
    "  /session share <id> [path] 导出已持久化会话转录",
    "  /tasks               列出工作区任务",
    "  /tasks panel [id]    显示任务面板或查看某个任务",
    "  /tasks add <text>    添加工作区任务",
    "  /tasks show <id>     显示单个工作区任务",
    "  /tasks update <id> --status <value> [--output <text>] ... 更新任务字段",
    "  /tasks output <id>   显示任务最近一次输出",
    "  /tasks stop <id> [reason] 取消任务并可记录原因",
    "  /tasks start <id>    将任务标记为进行中",
    "  /tasks done <id>     将任务标记为已完成",
    "  /tasks cancel <id>   将任务标记为已取消",
    "  /tasks remove <id>   删除任务",
    "  /tasks clear <mode>  清空 `completed` 或 `all` 任务",
    "  /model               显示当前会话模型",
    "  /model panel [name]  显示模型面板或查看某个档案",
    "  /model list          列出已配置模型档案",
    "  /model show [name]   显示当前或指定模型档案",
    "  /model use <name>    切换当前会话模型",
    "  /model default <name> 持久化默认模型档案",
    "  /permissions [mode] 显示或切换权限模式",
    "  /config              显示当前配置路径与解析后的配置",
    "  /config panel [key]  显示配置面板或聚焦某个解析后键",
    "  /config path|keys    显示当前配置路径或支持写入的键",
    "  /config set <key> <value> 更新一个支持的配置键",
    "  /config clear <key>  清除一个可选配置键",
    "  /resume [session-id] 列出可恢复会话或切换到指定会话",
    "  /share [path]        以 Markdown 导出当前转录",
    "  /compact [instructions] 用摘要上下文替换历史消息",
    "  /rewind             移除最近一轮对话",
    "  /clear               清空当前会话历史",
    "  /exit                退出 REPL",
];
