pub fn print_usage() {
    print_section(
        "Core local commands:",
        &[
            "hellox gateway serve",
            "hellox gateway print-default-config",
            "hellox brief show|set <message> [--attachment <path>]... [--status <text>] [--cwd <path>]",
            "hellox brief clear [--cwd <path>]",
            "hellox tools search <query> [--limit <n>]",
            "hellox config path|show|keys",
            "hellox config set <key> <value> [--config <path>]",
            "hellox config clear <key> [--config <path>]",
            "hellox plan show|enter|clear <session-id>",
            "hellox plan add-step <session-id> --step <status>:<text> [--index <n>]",
            "hellox plan update-step <session-id> <step-number> --step <status>:<text>",
            "hellox plan remove-step <session-id> <step-number>",
            "hellox plan allow|disallow <session-id> <prompt>",
            "hellox plan exit <session-id> --step <status>:<text> [--step <status>:<text>]... [--allow <prompt>]...",
            "hellox output-style list|show [style-name]|set-default <style-name>|clear-default",
            "hellox persona list|show [persona-name]|set-default <persona-name>|clear-default",
            "hellox prompt-fragment list|show [fragment-name]|set-default <name>...|clear-default",
            "hellox model list|show [profile-name]|set-default <profile-name>|save <profile-name> --provider <name> --upstream-model <name> [--display-name <name>] [--input-price <usd>] [--output-price <usd>] [--set-default]|remove <profile-name>",
            "hellox permissions show|set <mode>",
            "hellox doctor",
            "hellox status",
            "hellox usage",
            "hellox stats",
            "hellox cost",
            "hellox install [status|plan|apply] [--source <path>] [--target <path>] [--force]",
            "hellox upgrade [status|plan|apply] --source <path> [--target <path>] [--backup] [--force]",
            "hellox search <query> [--limit <n>]",
            "hellox chat \"<prompt>\"",
            "hellox repl",
            "hellox memory list [--archived]",
            "hellox memory show <memory-id> [--archived]",
            "hellox memory search <query> [--limit <n>] [--archived]",
            "hellox memory clusters [--archived] [--limit <n>] [--min-jaccard <v>] [--max-tokens <n>] [--semantic]",
            "hellox memory prune [--scope <all|session|project>] [--older-than-days <n>] [--keep-latest <n>] [--apply]",
            "hellox memory archive [--scope <all|session|project>] [--older-than-days <n>] [--keep-latest <n>] [--apply]",
            "hellox memory decay [--scope <all|session|project>] [--older-than-days <n>] [--keep-latest <n>] [--max-summary-lines <n>] [--max-summary-chars <n>] [--apply]",
            "hellox memory capture <session-id> [--instructions <text>]",
            "hellox session list",
            "hellox session show <session-id>",
            "hellox session compact <session-id> [--instructions <text>]",
            "hellox session share <session-id> [--output <path>]",
            "hellox tasks list [--status <value>] [--limit <n>] [--cwd <path>]",
            "hellox tasks show <task-id> [--cwd <path>]",
            "hellox tasks add <content> [--priority <value>] [--description <text>] [--cwd <path>]",
            "hellox tasks update <task-id> [--content <text>] [--priority <value>|--clear-priority] [--description <text>|--clear-description] [--status <value>] [--output <text>|--clear-output] [--cwd <path>]",
            "hellox tasks output <task-id> [--cwd <path>]",
            "hellox tasks stop <task-id> [--reason <text>] [--cwd <path>]",
            "hellox tasks start|done|cancel|remove <task-id> [--cwd <path>]",
            "hellox tasks clear (--completed | --all) [--cwd <path>]",
            "hellox workflow list [--cwd <path>]",
            "hellox workflow dashboard [workflow-name] [--script-path <path>] [--cwd <path>]",
            "hellox workflow overview [workflow-name] [--script-path <path>] [--cwd <path>]",
            "hellox workflow runs [workflow-name] [--script-path <path>] [--limit <n>] [--cwd <path>]",
            "hellox workflow validate [workflow-name] [--script-path <path>] [--cwd <path>]",
            "hellox workflow show-run <run-id> [--step <n>] [--cwd <path>]",
            "hellox workflow last-run [workflow-name] [--script-path <path>] [--step <n>] [--cwd <path>]",
            "hellox workflow show <workflow-name> [--script-path <path>] [--cwd <path>]",
            "hellox workflow init <workflow-name> [--cwd <path>] [--shared-context <text>] [--continue-on-error] [--force]",
            "hellox workflow add-step [--workflow <name> | --script-path <path>] --prompt <text> [--name <step-name>] [--index <n>] [--when <json>] [--model <name>] [--backend <name>] [--step-cwd <path>] [--run-in-background] [--cwd <path>]",
            "hellox workflow update-step [--workflow <name> | --script-path <path>] <step-number> [--name <step-name>|--clear-name] [--prompt <text>] [--when <json>|--clear-when] [--model <name>|--clear-model] [--backend <name>|--clear-backend] [--step-cwd <path>|--clear-step-cwd] [--run-in-background|--foreground] [--cwd <path>]",
            "hellox workflow remove-step [--workflow <name> | --script-path <path>] <step-number> [--cwd <path>]",
            "hellox workflow set-shared-context [--workflow <name> | --script-path <path>] <text> [--cwd <path>]",
            "hellox workflow clear-shared-context [--workflow <name> | --script-path <path>] [--cwd <path>]",
            "hellox workflow enable-continue-on-error|disable-continue-on-error [--workflow <name> | --script-path <path>] [--cwd <path>]",
            "hellox workflow run <workflow-name> [--script-path <path>] [--shared-context <text>] [--continue-on-error] [--config <path>] [--cwd <path>]",
        ],
    );
    println!();
    print_section(
        "Local integration commands:",
        &[
            "hellox bridge status|panel [session-id]|sessions|show-session <session-id>|stdio",
            "hellox ide status|panel",
            "hellox mcp list|show <server-name>",
            "hellox mcp tools|resources|prompts <server-name>",
            "hellox mcp call <server-name> <tool-name> [--input <json-object>]",
            "hellox mcp read-resource <server-name> <uri>",
            "hellox mcp get-prompt <server-name> <prompt-name> [--input <json-object>]",
            "hellox mcp auth-show|auth-clear <server-name>",
            "hellox mcp auth-set-token <server-name> --bearer-token <token>",
            "hellox mcp auth-oauth-set <server-name> --client-id <id> --authorize-url <url> --token-url <url> --redirect-url <url>",
            "hellox mcp auth-oauth-start|auth-oauth-refresh|auth-oauth-clear <server-name>",
            "hellox mcp auth-oauth-exchange <server-name> --code <code> --code-verifier <verifier>",
            "hellox mcp registry-list [--cursor <value>] [--limit <n>]",
            "hellox mcp registry-show <name>",
            "hellox mcp registry-install <name> [--server-name <local-name>] [--scope <scope>]",
            "hellox mcp add-stdio <server-name> --command <cmd> [--arg <arg>]...",
            "hellox mcp add-sse|add-ws <server-name> --url <url> [--header KEY=VALUE]... [--oauth-client-id <id> --oauth-authorize-url <url> --oauth-token-url <url> --oauth-redirect-url <url>]",
            "hellox mcp enable|disable|remove <server-name>",
            "hellox plugin list|show <plugin-id>",
            "hellox plugin install <path> [--disabled]",
            "hellox plugin enable|disable|remove <plugin-id>",
            "hellox plugin marketplace list|show <name>",
            "hellox plugin marketplace add <name> --url <url>",
            "hellox plugin marketplace enable|disable|remove <name>",
            "hellox skills [name]",
            "hellox hooks [name]",
            "hellox server serve [--config <path>]",
            "hellox server status [--config <path>]",
            "hellox server create-session [--config <path>] [--base-url <url>] [--session-id <id>] [--model <name>] [--cwd <path>]",
            "hellox server sessions [--config <path>]",
            "hellox server show-session <session-id> [--config <path>]",
        ],
    );
    println!();
    print_section(
        "User-managed remote commands:",
        &[
            "hellox auth status|accounts|show <account-id>",
            "hellox auth login <account-id> --access-token <token> [--provider <name>]",
            "hellox auth logout <account-id>",
            "hellox auth keys|set-key <provider> --api-key <key>|remove-key <provider>",
            "hellox sync settings-export <path> [--config <path>]",
            "hellox sync settings-import <path> [--config <path>]",
            "hellox sync team-memory-show <repo-id>",
            "hellox sync team-memory-panel <repo-id>",
            "hellox sync team-memory-export <repo-id> <path>",
            "hellox sync team-memory-import <repo-id> <path>",
            "hellox sync team-memory-put <repo-id> <key> <content>",
            "hellox sync team-memory-remove <repo-id> <key>",
            "hellox server managed-settings-show [--config <path>]",
            "hellox server managed-settings-set <config-toml-file> [--signature <value>] [--config <path>]",
            "hellox server policy-limits-show [--config <path>]",
            "hellox server policy-limits-set [--disable-command <name>]... [--disable-tool <name>]... [--notes <text>] [--config <path>]",
            "hellox server settings-show <account-id> [--config <path>]",
            "hellox server team-memory-show <account-id> <repo-id> [--config <path>]",
            "hellox server team-memory-panel <account-id> <repo-id> [--config <path>]",
            "hellox remote-env panel [name]|list|show <name>",
            "hellox remote-env add <name> --url <url> [--token-env <env>]",
            "hellox remote-env enable|disable|remove <name>",
            "hellox teleport panel|plan <environment-name> [--session-id <id>]",
            "hellox assistant list [--environment <name>] | show <session-id> [--environment <name>]",
        ],
    );
}

fn print_section(title: &str, commands: &[&str]) {
    println!("{title}");
    for command in commands {
        println!("  {command}");
    }
}
