use hellox_gateway_api::{extract_text, ContentBlock, Message, MessageContent, MessageRole};

/// Compression mode chosen for the current transcript.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompactMode {
    Micro,
    Full,
}

/// Result returned after compacting a transcript.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompactResult {
    pub mode: CompactMode,
    pub original_message_count: usize,
    pub retained_message_count: usize,
    pub summary: String,
}

/// Replace a transcript with a compact assistant summary that preserves the
/// latest intent, outcomes, and tool activity in a smaller context window.
pub fn compact_messages(messages: &mut Vec<Message>, instructions: Option<&str>) -> CompactResult {
    let original_message_count = messages.len();
    if messages.is_empty() {
        return CompactResult {
            mode: CompactMode::Micro,
            original_message_count: 0,
            retained_message_count: 0,
            summary: String::new(),
        };
    }

    let summary = build_summary(messages, instructions);
    messages.clear();
    messages.push(Message {
        role: MessageRole::Assistant,
        content: MessageContent::Text(summary.clone()),
    });

    CompactResult {
        mode: if original_message_count <= 4 {
            CompactMode::Micro
        } else {
            CompactMode::Full
        },
        original_message_count,
        retained_message_count: messages.len(),
        summary,
    }
}

fn build_summary(messages: &[Message], instructions: Option<&str>) -> String {
    let user_points = collect_points(messages, MessageRole::User, 4);
    let assistant_points = collect_points(messages, MessageRole::Assistant, 4);
    let tool_points = collect_tool_points(messages, 6);

    let mut sections = vec![
        "Conversation summary generated by hellox /compact.".to_string(),
        "Treat this summary as the authoritative context for earlier turns.".to_string(),
        format!("Original messages: {}", messages.len()),
    ];

    if let Some(instructions) = instructions
        .map(str::trim)
        .filter(|value| !value.is_empty())
    {
        sections.push(format!(
            "Compaction instructions: {}",
            collapse_whitespace(instructions)
        ));
    }

    sections.push(String::new());
    sections.push("Key user requests:".to_string());
    sections.extend(render_list(
        &user_points,
        "No explicit user requests captured.",
    ));

    sections.push(String::new());
    sections.push("Assistant outcomes:".to_string());
    sections.extend(render_list(
        &assistant_points,
        "No assistant outcomes captured.",
    ));

    sections.push(String::new());
    sections.push("Tool activity:".to_string());
    sections.extend(render_list(&tool_points, "No tool activity captured."));

    sections.join("\n")
}

fn collect_points(messages: &[Message], role: MessageRole, limit: usize) -> Vec<String> {
    let points = messages
        .iter()
        .filter(|message| same_role(&message.role, &role))
        .filter_map(|message| summarize_content(&message.content))
        .filter(|text| !text.is_empty())
        .collect::<Vec<_>>();
    tail_limited(points, limit)
}

fn collect_tool_points(messages: &[Message], limit: usize) -> Vec<String> {
    let mut points = Vec::new();

    for message in messages {
        if let MessageContent::Blocks(blocks) = &message.content {
            for block in blocks {
                match block {
                    ContentBlock::ToolUse { name, .. } => {
                        points.push(format!("Tool call: `{name}`"));
                    }
                    ContentBlock::ToolResult {
                        tool_use_id,
                        is_error,
                        ..
                    } => {
                        points.push(format!(
                            "Tool result: `{tool_use_id}`{}",
                            if *is_error { " (error)" } else { "" }
                        ));
                    }
                    _ => {}
                }
            }
        }
    }

    tail_limited(points, limit)
}

fn summarize_content(content: &MessageContent) -> Option<String> {
    let text = collapse_whitespace(&extract_text(content));
    if text.is_empty() {
        None
    } else {
        Some(truncate(&text, 180))
    }
}

fn render_list(items: &[String], empty_text: &str) -> Vec<String> {
    if items.is_empty() {
        return vec![format!("- {empty_text}")];
    }

    items.iter().map(|item| format!("- {item}")).collect()
}

fn tail_limited(items: Vec<String>, limit: usize) -> Vec<String> {
    let start = items.len().saturating_sub(limit);
    items.into_iter().skip(start).collect()
}

fn collapse_whitespace(input: &str) -> String {
    input.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn truncate(input: &str, max_len: usize) -> String {
    if input.chars().count() <= max_len {
        return input.to_string();
    }

    let truncated = input
        .chars()
        .take(max_len.saturating_sub(3))
        .collect::<String>();
    format!("{truncated}...")
}

fn same_role(left: &MessageRole, right: &MessageRole) -> bool {
    matches!(
        (left, right),
        (MessageRole::User, MessageRole::User) | (MessageRole::Assistant, MessageRole::Assistant)
    )
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::{compact_messages, CompactMode};
    use hellox_gateway_api::{Message, MessageContent, MessageRole};

    fn user(text: &str) -> Message {
        Message {
            role: MessageRole::User,
            content: MessageContent::Text(text.to_string()),
        }
    }

    fn assistant_text(text: &str) -> Message {
        Message {
            role: MessageRole::Assistant,
            content: MessageContent::Text(text.to_string()),
        }
    }

    fn assistant_tool() -> Message {
        Message {
            role: MessageRole::Assistant,
            content: serde_json::from_value(json!([
                {
                    "type": "tool_use",
                    "id": "tool-1",
                    "name": "Read",
                    "input": { "file_path": "src/main.rs" }
                }
            ]))
            .expect("tool use content"),
        }
    }

    #[test]
    fn compact_messages_returns_noop_for_empty_history() {
        let mut messages = Vec::new();
        let result = compact_messages(&mut messages, None);
        assert_eq!(result.original_message_count, 0);
        assert_eq!(result.retained_message_count, 0);
        assert!(result.summary.is_empty());
    }

    #[test]
    fn compact_messages_replaces_history_with_single_summary_message() {
        let mut messages = vec![
            user("implement compact command"),
            assistant_text("working on it"),
            assistant_tool(),
            user("also keep the latest tool activity"),
            assistant_text("done"),
        ];

        let result = compact_messages(&mut messages, Some("focus on current implementation state"));

        assert_eq!(result.mode, CompactMode::Full);
        assert_eq!(result.original_message_count, 5);
        assert_eq!(result.retained_message_count, 1);
        assert_eq!(messages.len(), 1);
        assert!(matches!(messages[0].role, MessageRole::Assistant));
        let MessageContent::Text(summary) = &messages[0].content else {
            panic!("expected compact summary text");
        };
        assert!(summary.contains("Conversation summary generated by hellox /compact."));
        assert!(summary.contains("Compaction instructions: focus on current implementation state"));
        assert!(summary.contains("Tool call: `Read`"));
    }

    #[test]
    fn compact_messages_marks_short_history_as_microcompact() {
        let mut messages = vec![user("hello"), assistant_text("hi")];
        let result = compact_messages(&mut messages, None);
        assert_eq!(result.mode, CompactMode::Micro);
    }
}
