use super::Replacement;

pub(super) const HEADING_REPLACEMENTS: &[Replacement] = &[
    (
        "Usage (user-managed remote capability):",
        "用法（用户管理的远程能力）：",
    ),
    ("Usage:", "用法："),
    ("Action palette", "操作面板"),
    ("REPL palette", "REPL 面板"),
    ("MCP server panel:", "MCP 服务器面板："),
    ("MCP panel", "MCP 面板"),
    ("Servers", "服务器"),
    ("Transport", "传输"),
    ("OAuth", "OAuth"),
];

pub(super) const ERROR_REPLACEMENTS: &[Replacement] = &[
    (
        "Unable to inspect persisted sessions",
        "无法检查已持久化会话",
    ),
    (
        "Unable to inspect workspace health",
        "无法检查工作区健康状态",
    ),
    ("Unable to inspect workspace usage", "无法检查工作区用量"),
    ("Unable to inspect workspace stats", "无法检查工作区统计"),
    (
        "Unable to load config for cost inspection",
        "无法为成本检查加载配置",
    ),
    ("Unable to inspect cost state", "无法检查成本状态"),
    (
        "Unable to search persisted sessions",
        "无法搜索已持久化会话",
    ),
    ("Unable to search memory files", "无法搜索记忆文件"),
    ("Unable to render bridge panel", "无法渲染 bridge 面板"),
    ("Unable to render memory panel", "无法渲染记忆面板"),
    ("Unable to render model panel", "无法渲染模型面板"),
    (
        "Unable to render output-style panel",
        "无法渲染输出风格面板",
    ),
    (
        "Unable to render output style panel",
        "无法渲染输出风格面板",
    ),
    ("Unable to render persona panel", "无法渲染人设面板"),
    (
        "Unable to render prompt fragment panel",
        "无法渲染提示片段面板",
    ),
    ("Unable to render session panel", "无法渲染会话面板"),
    ("Unable to render task panel", "无法渲染任务面板"),
    ("Unable to inspect output styles", "无法检查输出风格"),
    ("Unable to inspect personas", "无法检查人设"),
    ("Unable to inspect prompt fragments", "无法检查提示片段"),
    ("Unable to inspect tasks", "无法检查任务"),
    ("Unable to load output style", "无法加载输出风格"),
    ("Unable to load persona", "无法加载人设"),
    ("Unable to load prompt fragment", "无法加载提示片段"),
    ("Unable to load prompt fragments", "无法加载提示片段"),
    ("Unable to load memory", "无法加载记忆"),
    ("Unable to load", "无法加载"),
    ("Unable to share", "无法导出"),
    ("was not found", "未找到"),
    ("does not have OAuth configured", "没有配置 OAuth"),
    ("does not have a refresh token", "没有刷新令牌"),
    ("is disabled.", "已禁用。"),
    ("cannot be empty", "不能为空"),
    ("must be valid JSON.", "必须是有效 JSON。"),
    ("must be a JSON object.", "必须是 JSON 对象。"),
    ("JSON object", "JSON 对象"),
    ("Invalid MCP", "无效的 MCP"),
    ("Invalid selection.", "选择无效。"),
];

pub(super) const EMPTY_STATE_REPLACEMENTS: &[Replacement] = &[
    ("No tasks found.", "未找到任务。"),
    ("No memory files found.", "未找到记忆文件。"),
    ("No output styles found.", "未找到输出风格。"),
    ("No definitions found.", "未找到定义。"),
    ("No plugins installed.", "尚未安装插件。"),
    ("No plugin marketplaces configured.", "尚未配置插件市场。"),
    ("No remote environments configured.", "尚未配置远程环境。"),
    ("No remote sessions available.", "没有可用的远程会话。"),
    ("No model profiles configured.", "尚未配置模型档案。"),
    (
        "No persisted bridge sessions found.",
        "未找到已持久化的 bridge 会话。",
    ),
    ("No persisted sessions found.", "未找到已持久化会话。"),
    (
        "Start a session with persistence enabled first.",
        "请先启动启用持久化的会话。",
    ),
    (
        "No project workflow scripts found.",
        "未找到项目工作流脚本。",
    ),
    (
        "No workflow scripts found under",
        "未在以下路径找到工作流脚本",
    ),
    (
        "Create one with `hellox workflow init <name>` or `/workflow init <name>`.",
        "可使用 `hellox workflow init <name>` 或 `/workflow init <name>` 创建。",
    ),
];

pub(super) const AUTH_REPLACEMENTS: &[Replacement] = &[
    ("accounts:", "账号数："),
    ("provider_keys:", "Provider Key 数："),
    ("trusted_devices:", "已信任设备数："),
    ("No auth accounts stored.", "未保存 auth 账号。"),
    ("No provider keys stored.", "未保存 provider key。"),
    ("No trusted devices stored.", "未保存已信任设备。"),
    (
        "account_id\tprovider\tscopes\tupdated_at\texpires_at\taccess_token",
        "账号 ID\t供应商\t范围\t更新时间\t过期时间\t访问令牌",
    ),
    ("provider\tupdated_at\tapi_key", "供应商\t更新时间\tAPI Key"),
    (
        "device_id\taccount_id\tdevice_name\tscopes\tupdated_at\tdevice_token",
        "设备 ID\t账号 ID\t设备名称\t范围\t更新时间\t设备令牌",
    ),
    ("account_id:", "账号 ID："),
    ("provider:", "供应商："),
    ("access_token:", "访问令牌："),
    ("refresh_token:", "刷新令牌："),
    ("updated_at:", "更新时间："),
    ("expires_at:", "过期时间："),
    ("device_id:", "设备 ID："),
    ("device_name:", "设备名称："),
    ("device_token:", "设备令牌："),
    ("created_at:", "创建时间："),
    ("last_validated_at:", "上次校验时间："),
    ("(never)", "（从未）"),
    ("Stored auth account `", "已保存 auth 账号 `"),
    ("Removed auth account `", "已移除 auth 账号 `"),
    ("Stored provider key `", "已保存 provider key `"),
    ("Removed provider key `", "已移除 provider key `"),
    ("Removed trusted device `", "已移除已信任设备 `"),
];

pub(super) const SESSION_REPLACEMENTS: &[Replacement] = &[
    (
        "session_id\tmodel\tmessages\tupdated_at\tworking_directory",
        "会话 ID\t模型\t消息数\t更新时间\t工作目录",
    ),
    ("session_id:", "会话 ID："),
    ("model:", "模型："),
    ("permission_mode:", "权限模式："),
    ("output_style:", "输出风格："),
    ("persona:", "人设："),
    ("prompt_fragments:", "提示片段："),
    ("plan_mode: true", "计划模式： 已启用"),
    ("plan_mode: false", "计划模式： 未启用"),
    ("plan_mode:", "计划模式："),
    ("plan_steps:", "计划步骤数："),
    ("working_directory:", "工作目录："),
    ("shell:", "Shell："),
    ("messages:", "消息数："),
    ("requests:", "请求数："),
    ("input_tokens:", "输入 Token："),
    ("output_tokens:", "输出 Token："),
    ("(from current config)", "（沿用当前配置）"),
    ("bypass_permissions", "跳过权限"),
    ("accept_edits", "接受编辑"),
    ("read_only", "只读"),
    ("default", "默认"),
];

pub(super) const MEMORY_REPLACEMENTS: &[Replacement] = &[
    ("No memory hits for `", "未找到与 `"),
    (
        "memory_id\tscope\tage\tupdated_at\tpath",
        "记忆 ID\t范围\t时效\t更新时间\t路径",
    ),
    (
        "memory_id\tscope\tage\tscore\tlocation\tpreview\tpath",
        "记忆 ID\t范围\t时效\t分数\t位置\t预览\t路径",
    ),
    (
        "memory_id\tscope\tage\tupdated_at\taction\treason\tsource_path\tarchive_path",
        "记忆 ID\t范围\t时效\t更新时间\t动作\t原因\t源路径\t归档路径",
    ),
    (
        "memory_id\tscope\tage\tupdated_at\taction\treason\tsummary_before\tsummary_after\tpath",
        "记忆 ID\t范围\t时效\t更新时间\t动作\t原因\t摘要前\t摘要后\t路径",
    ),
    (
        "cluster_id\tseed_memory_id\tseed_preview\tmemory_id\tscope\tage\tupdated_at\tpreview\tpath",
        "聚类 ID\t种子记忆 ID\t种子预览\t记忆 ID\t范围\t时效\t更新时间\t预览\t路径",
    ),
    ("Would archive", "将归档"),
    ("Archived", "已归档"),
    ("Would decay", "将衰减"),
    ("Decayed", "已衰减"),
    ("stale archived memory file(s)", "个过期归档记忆文件"),
    ("stale memory file(s)", "个过期记忆文件"),
    ("for scope `", "，范围 `"),
    ("(older than ", "（超过 "),
    ("d, keep latest ", " 天，保留最新 "),
    (", max summary ", "，摘要上限 "),
    (" lines / ", " 行 / "),
    (" chars).", " 字符）。"),
    (").", "）。"),
    ("scanned\t", "扫描数\t"),
    ("kept\t", "保留数\t"),
    ("would-archive", "待归档"),
    ("would-decay", "待衰减"),
    ("decayed", "已衰减"),
    ("archived", "已归档"),
    ("older than ", "超过 "),
    (" and outside latest ", " 天，且超出最新保留 "),
    ("source_path", "源路径"),
    ("archive_path", "归档路径"),
    ("summary_before", "摘要前"),
    ("summary_after", "摘要后"),
    ("token_overlap", "词项重叠"),
    ("tfidf_cosine", "TF-IDF 余弦"),
    ("Clustered ", "已聚类 "),
    (" memory file(s) into ", " 个记忆文件为 "),
    (" cluster(s) (mode: ", " 个聚类（模式："),
    (", archived: ", "，归档："),
    (", limit: ", "，上限："),
    (", min_similarity: ", "，最小相似度："),
    (", max_tokens: ", "，最大 Token："),
    ("reason", "原因"),
    ("action", "动作"),
];

pub(super) const SEARCH_REPLACEMENTS: &[Replacement] = &[
    ("No search hits for `", "未找到 `"),
    ("`.", "` 的搜索结果。"),
    ("source\tsource_id\tlocation\tpreview", "来源\t来源 ID\t位置\t预览"),
    ("memory\t", "记忆\t"),
    ("session\t", "会话\t"),
    ("transcript\t", "转录\t"),
    ("message ", "第 "),
    ("line ", "第 "),
    ("score ", "分数 "),
    ("fresh <1m", "刚刚 <1 分钟"),
    ("fresh ", "刚刚 "),
    ("active ", "活跃 "),
    ("warm ", "近期 "),
    ("stale ", "过期 "),
    ("m)", " 分钟）"),
    ("h)", " 小时）"),
    ("d)", " 天）"),
    ("第  ", "第 "),
    ("第 1", "第 1"),
    ("第 2", "第 2"),
    ("第 3", "第 3"),
    ("第 4", "第 4"),
    ("第 5", "第 5"),
    ("第 6", "第 6"),
    ("第 7", "第 7"),
    ("第 8", "第 8"),
    ("第 9", "第 9"),
    ("第 0", "第 0"),
    ("第 1\t", "第 1 条消息\t"),
    ("第 2\t", "第 2 条消息\t"),
    ("第 3\t", "第 3 条消息\t"),
    ("第 4\t", "第 4 条消息\t"),
    ("第 5\t", "第 5 条消息\t"),
    ("第 6\t", "第 6 条消息\t"),
    ("第 7\t", "第 7 条消息\t"),
    ("第 8\t", "第 8 条消息\t"),
    ("第 9\t", "第 9 条消息\t"),
    ("第 0\t", "第 0 条消息\t"),
];
