use super::Replacement;

pub(super) const WORKFLOW_REPLACEMENTS: &[Replacement] = &[
    ("Closed workflow dashboard.", "已关闭工作流仪表板。"),
    ("Initialized workflow", "已初始化工作流"),
    ("Added workflow step", "已添加工作流步骤"),
    ("Updated workflow step", "已更新工作流步骤"),
    ("Duplicated workflow step", "已复制工作流步骤"),
    ("Moved workflow step", "已移动工作流步骤"),
    ("Removed workflow step", "已移除工作流步骤"),
    ("Updated shared_context.", "已更新 shared_context。"),
    ("Cleared shared_context.", "已清除 shared_context。"),
    ("Enabled continue_on_error.", "已启用 continue_on_error。"),
    ("Disabled continue_on_error.", "已禁用 continue_on_error。"),
    ("workflow run `", "工作流运行 `"),
    ("workflow `", "工作流 `"),
    ("has no steps to focus yet.", "还没有可聚焦的步骤。"),
    ("has no recorded steps.", "没有已记录的步骤。"),
    ("Focused workflow step", "已聚焦工作流步骤"),
    ("Focused recorded step", "已聚焦已记录步骤"),
    ("Already on the first workflow step", "已在第一个工作流步骤"),
    (
        "Already on the last workflow step",
        "已在最后一个工作流步骤",
    ),
    ("Already on the first recorded step", "已在第一个已记录步骤"),
    (
        "Already on the last recorded step",
        "已在最后一个已记录步骤",
    ),
    (" into step ", " 复制为步骤 "),
    (" to step ", " 到步骤 "),
    (" of ", " / "),
    (" at `", "，位置 `"),
    (
        "choose either `<name>` or `--script-path <path>` for",
        "请为以下命令在 `<name>` 与 `--script-path <path>` 中选择一个：",
    ),
];

pub(super) const MCP_REPLACEMENTS: &[Replacement] = &[
    ("No MCP servers configured.", "尚未配置 MCP 服务器。"),
    ("Stored MCP bearer token for", "已保存 MCP bearer token："),
    ("Cleared MCP bearer token for", "已清除 MCP bearer token："),
    (
        "No stored MCP bearer token found for",
        "未找到已保存的 MCP bearer token：",
    ),
    ("Configured MCP OAuth for", "已配置 MCP OAuth："),
    ("Refreshed MCP OAuth account", "已刷新 MCP OAuth 账号"),
    (
        "Cleared linked MCP OAuth account for",
        "已清除已关联的 MCP OAuth 账号：",
    ),
    (
        "OAuth client config remains in",
        "OAuth 客户端配置仍保留在",
    ),
    (
        "No linked MCP OAuth account found for",
        "未找到已关联的 MCP OAuth 账号：",
    ),
    ("Installed MCP registry server", "已安装 MCP 注册表服务器"),
    ("Added MCP server", "已添加 MCP 服务器"),
    ("Enabled MCP server", "已启用 MCP 服务器"),
    ("Disabled MCP server", "已禁用 MCP 服务器"),
    ("Removed MCP server", "已移除 MCP 服务器"),
    ("MCP server `", "MCP 服务器 `"),
    ("Stored MCP OAuth account `", "已保存 MCP OAuth 账号 `"),
    ("MCP OAuth account `", "MCP OAuth 账号 `"),
    (
        "MCP OAuth is only supported for HTTP/SSE or WebSocket servers.",
        "MCP OAuth 仅支持 HTTP/SSE 或 WebSocket 服务器。",
    ),
    (
        "MCP bearer-token helper only supports HTTP/SSE or WebSocket servers configured with `transport = \"sse\"` or `transport = \"ws\"`.",
        "MCP bearer-token 助手仅支持配置为 `transport = \"sse\"` 或 `transport = \"ws\"` 的 HTTP/SSE 或 WebSocket 服务器。",
    ),
    ("Unknown MCP error", "未知 MCP 错误"),
    ("MCP error", "MCP 错误"),
    ("server:", "服务器："),
    ("authorization_url:", "授权 URL："),
    ("code_verifier:", "code_verifier："),
    ("state:", "state："),
    ("tool:", "工具："),
    ("prompt:", "提示："),
    ("result:", "结果："),
    ("tools:", "工具："),
    ("resources:", "资源："),
    ("prompts:", "提示："),
    ("uri:", "URI："),
    ("content_uri:", "内容 URI："),
    ("mime_type:", "MIME 类型："),
    ("text:", "文本："),
    ("blob_base64_length:", "blob base64 长度："),
    (
        "name\tenabled\ttransport\tscope\tdescription",
        "名称\t启用\t传输\t范围\t描述",
    ),
];

pub(super) const STYLE_REPLACEMENTS: &[Replacement] = &[
    ("Active output style set to", "当前会话输出风格已设置为"),
    ("Cleared active output style", "已清除当前输出风格"),
    (
        "No active output style is set for the current session.",
        "当前会话没有设置输出风格。",
    ),
    ("Active persona set to", "当前会话人设已设置为"),
    ("Cleared active persona", "已清除当前人设"),
    (
        "No active persona is set for the current session.",
        "当前会话没有设置人设。",
    ),
    ("Active prompt fragments set to", "当前会话提示片段已设置为"),
    ("Cleared active prompt fragments", "已清除当前提示片段"),
    (
        "No active prompt fragments are set for the current session.",
        "当前会话没有设置提示片段。",
    ),
    ("for the current session", "（当前会话）"),
];

pub(super) const TASK_REPLACEMENTS: &[Replacement] = &[
    ("Added task", "已添加任务"),
    ("Updated task", "已更新任务"),
    ("Stopped task", "已停止任务"),
    ("Marked task", "已将任务"),
    ("Removed task", "已移除任务"),
    (" task(s).", " 个任务。"),
    (" as ", " 标记为 "),
    ("task_id:", "任务 ID："),
    ("status:", "状态："),
    ("priority:", "优先级："),
    ("content:", "内容："),
    ("description:", "描述："),
    ("output:", "输出："),
];

pub(super) const PLUGIN_REMOTE_REPLACEMENTS: &[Replacement] = &[
    ("Installed plugin", "已安装插件"),
    ("Enabled plugin marketplace", "已启用插件市场"),
    ("Disabled plugin marketplace", "已禁用插件市场"),
    ("Removed plugin marketplace", "已移除插件市场"),
    ("Added plugin marketplace", "已添加插件市场"),
    ("Enabled plugin", "已启用插件"),
    ("Disabled plugin", "已禁用插件"),
    ("Removed plugin", "已移除插件"),
    ("Added remote environment", "已添加远程环境"),
    ("Enabled remote environment", "已启用远程环境"),
    ("Disabled remote environment", "已禁用远程环境"),
    ("Removed remote environment", "已移除远程环境"),
    ("Remote environment `", "远程环境 `"),
    (
        "Open the local assistant viewer panel",
        "打开本地 assistant 查看面板",
    ),
    (
        "Show the local/remote assistant session viewer",
        "显示本地/远程 assistant 会话查看器",
    ),
    (
        "Inspect one assistant-viewable session",
        "查看一个可由 assistant 查看器读取的会话",
    ),
];

pub(super) const LABEL_REPLACEMENTS: &[Replacement] = &[
    ("active_output_style:", "当前输出风格："),
    ("default_output_style:", "默认输出风格："),
    ("active_persona:", "当前人设："),
    ("default_persona:", "默认人设："),
    ("active_prompt_fragments:", "当前提示片段："),
    ("default_prompt_fragments:", "默认提示片段："),
    ("workspace_root:", "工作区根目录："),
    ("provider:", "供应商："),
    ("client_id:", "client_id："),
    ("authorize_url:", "授权 URL："),
    ("token_url:", "令牌 URL："),
    ("redirect_url:", "重定向 URL："),
    ("scopes:", "范围："),
    ("login_hint:", "登录提示："),
    ("account_id:", "账号 ID："),
    ("enabled:", "启用："),
    ("scope:", "范围："),
    ("transport:", "传输："),
    ("oauth:", "OAuth："),
    ("command:", "命令："),
    ("args:", "参数："),
    ("cwd:", "cwd："),
    ("env:", "环境变量："),
    ("headers:", "请求头："),
    ("url:", "URL："),
    ("config_path", "配置路径"),
    ("oauth_configured", "OAuth 已配置"),
    ("YES", "是"),
    ("NO", "否"),
    ("(none)", "（无）"),
    ("(unknown)", "（未知）"),
    ("(unnamed)", "（未命名）"),
    ("(inherit current process)", "（继承当前进程）"),
    ("configured", "已配置"),
];
